spring:
  application:
    name: event-module
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: ${datasource_url}
    username: ${u_pg}
    password: ${p_pg}
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  # profiles:
  #   active: dev

server:
  port: 8066

# Files storage location (stores all file uploaded via REST), see the StorageProperties class
storage:
  location: ${user.home}/event-module-uploads
