application:
  name: event-module
spring:
  cloud:
    compatibility:
      enabled: false
    vault:
      enabled: true
      host: 154.125.255.110
      port: 8200
      scheme: http
      token: c6fc5310-88f9-4ed2-2393-8eb9a8dfdaed
    kv:
      enabled: true
  config:
    import: optional:vault://

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/event-module
    username: ${u_pg}
    password: ${p_pg}
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # properties:
    #   hibernate:
    #     default_schema: EVENT_DB
    show-sql: true
    hibernate:
    #   naming:
    #     physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

  # For database initialization
  # sql:
  #   init:
  #     mode: always
server:
  port: 8082
  # SSL config (mode https)
    #ssl:
    #  key-store: classpath:certs/WildCard2023.PFX
    #  key-store-type: PKCS12
    #  key-store-password: 123456789
  #  key-password: 123456789

# Application specific properties.
# Add your own application properties here, see the ApplicationProperties class

# Files storage location (stores all file uploaded via REST), see the StorageProperties class
storage:
  location: ${user.home}/event-module-uploads